version: "3.8"
services:
  app:
    build: .
    ports:
      - "9292:9292"
    volumes:
      - .:/app:cached
      - gem-cache:/bundle:cached
    stdin_open: true
    tty: true
volumes:
  gem-cache:
    driver: local