# frozen_string_literal: true

source 'https://rubygems.org'

# Core gems
gem 'rack'
gem 'rackup'

# Env management
gem 'dotenv'

# Session management
gem 'rack-session', '~> 2'

# Mism
gem 'require_all'

# Development
group :development do
  gem 'byebug'
  gem 'rubocop'
end
