# frozen_string_literal: true

source 'https://rubygems.org'

# Gemas core
gem 'puma'
gem 'rack'
gem 'rackup'

# Manejo de variables de entorno
gem 'dotenv'

# Manejo de sesiones
gem 'rack-session', '~> 2'

# Misc
gem 'require_all'

# Desarrollo
group :development do
  gem 'byebug'
  gem 'rubocop'
end

# Tests
group :test do
  gem 'json-schema'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-openapi'
end
