# frozen_string_literal: true

source 'https://rubygems.org'

# Core gems
gem 'puma'
gem 'rack'
gem 'rackup'

# Env management
gem 'dotenv'

# Session management
gem 'rack-session', '~> 2'

# Misc
gem 'require_all'

# Development
group :development do
  gem 'byebug'
  gem 'rubocop'
end

group :test do
  gem 'json-schema'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-openapi'
end
